server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: kafka-logs
    kafka:
      brokers:
        - localhost:9092
      topics:
        - ingestion-logs
      group_id: promtail-consumer
      labels:
        job: kafka-logs
    pipeline_stages:
      - json:
          expressions:
            etat: Etat
            source: Source
            entreprise: Entreprise
            zone: Zone
      - labels:
          etat: etat
          source: source
          entreprise: entreprise
          zone: zone